apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-prod
  namespace: argocd
  labels:
    app: sample-app-prod
    version: v1
spec:
  project: default
  source:
    repoURL: https://github.com/maheshforce/new-poc.git
    targetRevision: main
    path: helm/sample-app
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
